### PR TITLE
Fix #22 reuse folder has incorrect name

### LINKED ISSUE #22: [rl-reuse_tool-4] Violation against OSS Rules of Play
A violation against the OSS Rules of Play has been detected.

Rule ID: rl-reuse_tool-4
Explanation: Is it compliant with REUSE rules? **No**

Find more information at: https://sap.github.io/fosstars-rating-core/oss_rules_of_play_rating.html

### PR DESCRIPTION
**Pull request by dellagustin-sap**
**Description**

Changes proposed in this pull request:

- Renamed `reuse` folder to fix REUSE compliance (https://api.reuse.software/info/github.com/kyma-project/infrastructure-manager)

**Related issue(s)**

Fixes #22 

Tested with docker, command: `docker run --rm --volume $(pwd):/data fsfe/reuse lint`

### CODE REVIEW

**Comment by dellagustin-sap** [comment]
I tried signing the CLA, but there seems to be a problem.
I get the screen below but cannot get past it:
image

**Comment by Disper** [comment]
Hi @dellagustin-sap, 
thank you for your PR ❤️! 

I've kicked the jobs to run and I see that the unit tests have failed, but it's highly unlikely that this PR has caused the error. We will investigate that.

**Comment by Disper** [comment]
**Update:** I've confirmed that "Gardener Cluster controller"."Secret with kubeconfig exists"."Force rotation" test is flaky.

**Review by Disper — APPROVED** [review]
LGTM
/meow

**Comment by Disper** [comment]
Flaky tests were fixed in #63

**Review by m00g3n — APPROVED** [review]

**Pull request merged**
